Table user {
    id int [pk]
    //is_watched int [not null] //FK
    //is_liked int [not null] //FK
    //is_saved int [not null] //FK
}

Table user_interactions {
    id int [pk]
}

Table films {
    id int [pk]
    title varchar
}

Table tv_show {
    id int [pk]
    title varchar

}

Table actor {
    id int [pk]
    first_name varchar
    last_name varchar
    
}

Table director {
    id int [pk]
    first_name varchar
    last_name varchar

}

Table film_actors{
    id int [pk]
    actor_id int [not null] //FK
    films_id int [not null] //FK
}

Table tv_actors{
    id int [pk]
    actor_id int [not null] //FK
    tv_show_id int [not null] //FK
}

Table film_directors{
    id int [pk]
    director_id int [not null] //FK
    films_id int [not null] //FK
}

Table tv_directors{
    id int [pk]
    director_id int [not null] //FK
    tv_show_id int [not null] //FK
}
Ref film_actors: film_actors.actor_id > actor.id
Ref tv_actors: tv_actors.actor_id > actor.id

Ref film_directors: film_directors.director_id > director.id
Ref tv_directors: tv_directors.director_id > director.id

Ref film_actors: film_actors.films_id > films.id
Ref film_directors: film_directors.films_id > films.id

Ref tv_actors: tv_actors.tv_show_id > tv_show.id
Ref tv_directors: tv_directors.tv_show_id > tv_show.id